[WIP] No one can view or edit with a invite code that has been fully submitted
cds-snc/cppd-medical-report-sails pull request #145
Opened 2020-02-12 14:29 UTC by jeffmaher

Working on [Trello card](https://trello.com/c/MOaKInr8/498-noone-can-edit-the-report-after-it-has-been-submitted), will add more details after this is ready for review.

Is a follow-on to #140 .

2020-02-13 15:45 UTC, keithiopia commented on config/locales/en.json
> +	"errors.application_submitted_already": "A medical report has already been submitted using the unique code you entered and connect be accessed. Call Service Canada at 1-800-277-9914 if you have any
```suggestion
	"errors.application_submitted_already": "A medical report has already been submitted using the unique code you entered and cannot be accessed. Call Service Canada at 1-800-277-9914 if you have any questions."
```

2020-02-13 15:46 UTC, keithiopia requested changes
Small typo.

Also, I'm shown the error message the first time I enter the invitation code and date of birth.

2020-02-13 20:08 UTC, kylejones-ESDC reviewed
I am receiving the error code in question "A medical report has already been submitted using the unique code you entered and connect be accessed. Call Service Canada at 1-800-277-9914 if you have any questions." when attempting to begin the medical report, prior to having ever completed a medical report using that code.

2020-02-14 14:47 UTC, jeffmaher commented
Thanks for the feedback! Will investigate.

2020-02-17 21:54 UTC, jeffmaher commented
I think I got the bug fixed! Ready for re-review from @keithiopia and @kylejones-ESDC .

2020-02-18 18:15 UTC, kylejones-ESDC submitted a review, later dismissed
Some small bugs noted, Trello cards created.

The stated functionality works as indicated.

2020-02-19 15:52 UTC, keithiopia submitted a review, later dismissed
Looks about right to me!

2020-02-19 19:23 UTC, CalvinRodo submitted a review, later dismissed
LGTM!

2020-02-19 22:28 UTC, dsamojlenko approved these changes

2020-02-20 00:45 UTC, merged